// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929005955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocalGoals")
                        .HasColumnType("integer");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitorGoals")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId", "MatchId")
                        .IsUnique();

                    b.ToTable("Bets", t =>
                        {
                            t.HasCheckConstraint("CK_Bet_PointsEarned", "\"PointsEarned\" IN (0, 1, 3)");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LocalGoals")
                        .HasColumnType("integer");

                    b.Property<int>("LocalTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VisitorGoals")
                        .HasColumnType("integer");

                    b.Property<int>("VisitorTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalTeamId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Matches", t =>
                        {
                            t.HasCheckConstraint("CK_Match_DifferentTeams", "\"LocalTeamId\" <> \"VisitorTeamId\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = 8,
                            LocalTeamId = 5,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 6
                        },
                        new
                        {
                            Id = 9,
                            LocalTeamId = 7,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 8
                        },
                        new
                        {
                            Id = 10,
                            LocalTeamId = 5,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 7
                        },
                        new
                        {
                            Id = 11,
                            LocalTeamId = 6,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 8
                        },
                        new
                        {
                            Id = 12,
                            LocalTeamId = 8,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 5
                        },
                        new
                        {
                            Id = 13,
                            LocalTeamId = 6,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 7
                        },
                        new
                        {
                            Id = 14,
                            LocalTeamId = 1,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            LocalTeamId = 3,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 4
                        },
                        new
                        {
                            Id = 16,
                            LocalTeamId = 1,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 3
                        },
                        new
                        {
                            Id = 17,
                            LocalTeamId = 2,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 4
                        },
                        new
                        {
                            Id = 18,
                            LocalTeamId = 4,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 1
                        },
                        new
                        {
                            Id = 19,
                            LocalTeamId = 2,
                            Status = "UpcomingMatch",
                            VisitorTeamId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bayern München"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Inter de Milán"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 6,
                            Name = "FC Barcelona"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Arsenal"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "player1@player.com",
                            Name = "Juan Díaz",
                            PasswordHash = "$2b$11$DaqubqB.PVWKKtzFqBknAuef4ywFvt5XO5EtRsM.8/4p/IpCud2Ca",
                            Role = "Player"
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin@admin.com",
                            Name = "Luisa Perez",
                            PasswordHash = "$2b$11$DaqubqB.PVWKKtzFqBknAuef4ywFvt5XO5EtRsM.8/4p/IpCud2Ca",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "player@player.com",
                            Name = "Mario Torres",
                            PasswordHash = "$2b$11$DaqubqB.PVWKKtzFqBknAuef4ywFvt5XO5EtRsM.8/4p/IpCud2Ca",
                            Role = "Player"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bet", b =>
                {
                    b.HasOne("Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Match", b =>
                {
                    b.HasOne("Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("LocalTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
